create or replace package GESTION_AERONAVE IS
FUNCTION FN_VALIDA_ELIMINACION(pCodAeronave IN CHAR)
RETURN CHAR;

END;
/
create or replace package body GESTION_AERONAVE IS

FUNCTION FN_VALIDA_ELIMINACION(pCodAeronave IN CHAR)
RETURN CHAR
IS
VFLAG CHAR;
VCANTIDAD INTEGER;
BEGIN

VFLAG:='N';
SELECT COUNT(1) INTO VCANTIDAD FROM CAB_CARGA CA WHERE CA.IDNAVE=pCodAeronave;
IF VCANTIDAD>0 THEN

VFLAG:='S';
END IF;

RETURN VFLAG;
EXCEPTION WHEN OTHERS THEN

RETURN VFLAG;
END;


END;
/
