--DATA MAESTRA PREDEFINIDA POR EL CLIENTE -BY CESAR HUANES 12/04/2016
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('01', 'OPERACIONES');
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('02', 'AERONAVE. CONTINUA');
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('03', 'OMA 75');
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('04', 'OTRO OMA');
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('05', 'CLIENTE');
insert into TBL_AREA_RESPONSABLE (COD_AREA_RESPONSABLE, NOM_AREA_RESPONSABLE)
values ('06', 'OTROS');
commit;

insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0001', 'AMAN: Maniobra brusca');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0002', 'ARC: Contacto anormal con la pista');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0003', 'CFIT: Vuelo controlado contra el terreno');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0004', 'EVAC: Evacuación');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0005', 'F-NI: Fuego/humo (sin impacto)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0006', 'F-POST: Fuego/humo (tras el impacto)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0007', 'FUEL: Relativo a combustible');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0008', 'RAMP: Asistencia a la aeronave (handling)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0009', 'GCOL: Colisión en tierra');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0010', 'ICE: Engelamiento');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0011', 'LALT: Operaciones a baja altura');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0012', 'LOC-G: Pérdida de control en tierra');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0013', 'LOC-I: Pérdida de control en vuelo');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0014', 'MAC: AIRPROX/casi colisión/colisión en el aire');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0015', 'RE: Salida de pista');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0018', 'SCF-NP: Fallo o malfuncionamiento de un sistema o componente de la aeronave (no motor)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0019', 'SCF-PP: Fallo o malfuncionamiento del motor');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0020', 'SEC: Relacionado con la segudidad física (security)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0021', 'TURB: Encuentro con turbulencia');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0022', 'USOS: Aterrizajes cortos/rebasando final de pista');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0023', 'WSTRW: Cizalladura y tormenta');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0024', 'ADRM: Aeródromo');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0025', 'ATM: ATM/CNS');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0026', 'CABIN: Eventos de seguridad en cabina');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0027', 'RI-A: Incursión de animal en pista');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0028', 'RI-VAP:Incursión de aeronave, vehículo o persona en pista');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0029', 'BIRD: Impacto con aves (birdstrike)');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0098', 'OTHR: Otros');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0099', 'UNK: Desconocido o indeterminado');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0100', 'UIMC: Vuelo inintencionado en IMC');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0101', 'EXTL: Sucesos relativos a carga externa');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0102', 'CTOL: Colisión con obstáculos durante el despegue y el aterrizaje');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0103', 'LOLI: Pérdida de condiciones de sustentación en ruta.');
insert into TBL_CATEGORIA_SUCESO (COD_CATEGORIA, NOM_CATEGORIA)
values ('0104', 'GTOW: Eventos relativos al remolcado de planeadores');
commit;

insert into TBL_CLASE_SUCESO (COD_CLASE_SUCESO, NOM_CLASE_SUCESO, DESC_CLASE_SUCESO)
values ('300 ', 'INCIDENTE', 'SUCESO, DISTINTO DE UN ACCIDENTE, ASOCIADO CON LA OPERACIÓN DE UNA AERONAVE QUE AFECTA O PODRÍA AFECTAR A LA SEGURIDAD DE OPERACIÓN.  NOTA.—  EL TIPO DE INCIDENTES QUE SON DE ESPECIAL INTERÉS PARA LA ORGANIZACIÓN INTERNACIONAL DE AVIACIÓN CIVIL (OACI) PARA LOS ESTUDIOS DE PREVENCIÓN DE ACCIDENTES, ENUMERADOS EN EL MANUAL DE NOTIFICACIÓN DE ACCIDENTES/INCIDENTES DE LA OACI (DOC 9156 DE LA OACI) Y EN EL ANEXO 13 DE LA OACI.');
insert into TBL_CLASE_SUCESO (COD_CLASE_SUCESO, NOM_CLASE_SUCESO, DESC_CLASE_SUCESO)
values ('301 ', 'INCIDENTE MAYOR', 'EUROCONTROL: INCIDENTE ASOCIADO CON LA OPERACIÓN DE UNA AERONAVE, EN EL QUE LA SEGURIDAD DE LA AERONAVE PODRÍA HABER ESTADO COMPROMETIDA, LO CUAL PODRÍA HABER DERIVADO EN UNA POSIBLE COLISIÓN DE LA AERONAVE CON TIERRA U OBSTÁCULOS (P. EJ., MÁRGENES DE SEGURIDAD NO RESPETADOS, NO A CONSECUENCIA DE UNA INSTRUCCIÓN ATC).');
insert into TBL_CLASE_SUCESO (COD_CLASE_SUCESO, NOM_CLASE_SUCESO, DESC_CLASE_SUCESO)
values ('302 ', 'NO DETERMINADO', 'NO DETERMINADO');
insert into TBL_CLASE_SUCESO (COD_CLASE_SUCESO, NOM_CLASE_SUCESO, DESC_CLASE_SUCESO)
values ('400 ', 'SUCESO SIN EFECTO EN LA SEGURIDAD', 'SUCESO POSIBLEMENTE RELACIONADO CON LA SEGURIDAD QUE NO CUMPLE CON LOS REQUISITOS DE NOTIFICACIÓN. ESTO PODRÍA SER, P. EJ., A CAUSA DE LA RECLASIFICACIÓN EN UN NIVEL INFERIOR DEL ACCIDENTE DESPUÉS DE SU REVISIÓN.  EUROCONTROL: INCIDENTE NO RELEVANTE PARA LA SEGURIDAD.  NOTA.—  ESTO PARECE ESTAR EN CONTRADICCIÓN CON LA DEFINICIÓN DE LA OACI DE UN INCIDENTE: SUCESO, DIFERENTE A UN ACCIDENTE, ASOCIADO CON LA OPERACIÓN DE UNA AERONAVE QUE AFECTA O PODRÍA AFECTAR A LA SEGURIDAD DE OPERACIÓN.');
insert into TBL_CLASE_SUCESO (COD_CLASE_SUCESO, NOM_CLASE_SUCESO, DESC_CLASE_SUCESO)
values ('500 ', 'ACCIDENTE', 'ACCIDENTE');
commit;

insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('01', 'AMAZONAS', 'AMAZ ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('02', 'ÁNCASH', 'ANCA ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('03', 'APURÍMAC', 'APUR ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('04', 'AREQUIPA', 'AREQ ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('05', 'AYACUCHO', 'AYAC ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('06', 'CAJAMARCA', 'CAJA ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('07', 'CUSCO', 'CUSC ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('08', 'HUANCAVELICA', 'HUANC');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('09', 'HUÁNUCO', 'HUANU');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('10', 'ICA', 'ICA  ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('11', 'JUNÍN', 'JUN  ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('12', 'LA LIBERTAD', 'LIBER');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('13', 'LAMBAYEQUE', 'LAMB ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('14', 'LIMA', 'LIMA ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('15', 'LORETO', 'LORE ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('16', 'MADRE DE DIOS', 'MDIO ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('17', 'MOQUEGUA', 'MOQU ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('18', 'PASCO', 'PASC ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('19', 'PIURA', 'PIUR ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('20', 'PUNO', 'PUNO ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('21', 'SAN MARTÍN', 'SMAR ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('22', 'TACNA', 'TACN ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('23', 'TUMBES', 'TUMB ');
insert into TBL_DEPARTAMENTO (COD_DEPARTAMENTO, NOM_DEPARTAMENTO, ABRE_DEPARTAMENTO)
values ('24', 'UCAYALI', 'UCAY ');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1000000   ', 'AERONAVE/SISTEMA/COMPONENTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1010000   ', '0100 PRESTACIONES DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1010100   ', '0101 DEGRACIÓN DE PRESTACIONES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1090000   ', '0900 RELACIONADO CON EL EQUIPO DE REMOLCADO Y RODAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1091000   ', '0910 REMOLCADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1091001   ', 'ROTURA DE BARRA/CABLE DE REMOLCADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1100000   ', '1000 ESTACIONAMIENTO Y ANCLAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1110000   ', '1100 RÓTULOS Y MARCAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1120000   ', '1200 SERVICIO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1180000   ', '1800 ANÁLISIS DE VIBRACIÓN/RUIDO EN HELICÓPTERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1180100   ', '1810 ANÁLISIS DE VIBRACIÓN EN HELICÓPTERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1182000   ', '1820 ANÁLISIS DE RUIDO EN HELICÓPTERO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1210000   ', '2100 AIRE ACONDICIONADO Y PRESURIZACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1220000   ', '2200 SISTEMA AUTOMÁTICO DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1230000   ', '2300 SISTEMA DE COMUNICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1240000   ', '2400 SISTEMA DE ALIMENTACIÓN ELÉCTRICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1250000   ', '2500 EQUIPAMIENTO/MOBILIARIO DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1251000   ', '2510 COMPARTIMIENTO DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1252000   ', '2520 COMPARTIMIENTO DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1253000   ', '2530 COCINAS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1254000   ', '2540 LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255000   ', '5000 COMPARTIMIENTOS DE CARGA Y ACCESORIOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255900   ', '5019 RELACIONADO CON LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255901   ', 'FUGA/PÉRDIDA DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255902   ', 'DESPLAZAMIENTO DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255903   ', 'HUMO/VAPORES/GASES/INCENDIO DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255904   ', 'FUGA DE RADIACIÓN DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1255905   ', 'CAÍDA DE CARGA/CARGA SUSPENDIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1256500   ', '2565 RAMPA DE EVACUACIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1260000   ', '2600 SISTEMA DE PROTECCIÓN CONTRA INCENDIOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1270000   ', '2700 MANDOS DE VUELO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1280000   ', '2800 SISTEMA DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1280100   ', '2801 FUGA DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1290000   ', '2900 SISTEMA HIDRÁULICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1300000   ', '3000 SISTEMA DE PROTECCIÓN CONTRA HIELO/LLUVIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1310000   ', '3100 SISTEMAS DE INDICACIÓN/REGISTRO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1313000   ', '3130 REGISTRO DE DATOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1315000   ', '3150 SISTEMA CENTRAL DE AVISOS (WARNING SYSTEM)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1320000   ', '3200 TREN DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1321000   ', '3210 TREN DE ATERRIZAJE PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1321001   ', 'TREN DE ATERRIZAJE PRINCIPAL - REPLIEGUE/RETRACCIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1321002   ', 'TREN DE ATERRIZAJE PRINCIPAL - REPLIEGUE O RETRACCIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1322000   ', '3220 TREN DE ATERRIZAJE DE MORRO/COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1322001   ', 'TREN DE ATERRIZAJE DE MORRO/COLA - REPLEGADO/RETRAÍDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324000   ', '3240 RUEDAS Y FRENOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324100   ', '3244 NEUMÁTICOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324200   ', '3242 FRENOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324207   ', 'FRENO DE ESTACIONAMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324214   ', 'FRENO DE EMERGENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1324400   ', '3241 SISTEMA ANTIDERRAPANTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1325000   ', '3250 DIRECCIÓN DEL TREN DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1326000   ', '3260 POSICIÓN Y AVISO DEL TREN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1327000   ', '3270 TREN DE ATERRIZAJE AUXILIAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1327001   ', 'REPLIEGUE DEL TREN-OTRO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1330000   ', '3300 ILUMINACIÓN DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1340000   ', '3400 SISTEMAS DE NAVEGACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1341400   ', '3414 SISTEMA DE INDICACIÓN DE VELOCIDAD AERODINÁMICA/MACH');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1341600   ', '3416 SISTEMA DE ALTITUD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1341800   ', '3460 SISTEMA DE GESTIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1342000   ', '3420 SISTEMA DE DATOS DE ACTITUD Y DIRECCIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1343000   ', '3430 AYUDAS AL ATERRIZAJE Y RODAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344000   ', '3440 SISTEMA INDEPENDIENTE DE POSICIONAMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344400   ', '3444 AVISO DE PROXIMIDAD DEL TERRENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344401   ', 'ALARMA MOLESTA DEL GPWS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344402   ', 'OTRO EVENTO DEL GPWS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344500   ', '3445 ACAS/TCAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1344501   ', 'ALARMA MOLESTA DEL TCAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1350000   ', '3500 SISTEMA DE OXÍGENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1360000   ', '3600 SISTEMA NEUMÁTICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1370000   ', '3700 SISTEMA DE VACÍO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1380000   ', '3800 SISTEMA DE AGUA POTABLE/RESIDUAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1490000   ', '4900 GRUPO DE POTENCIA AUXILIAR (APU)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1510000   ', '5100 PRÁCTICAS Y ESTRUCTURAS ESTÁNDAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1510100   ', '5101 ESTRUCTURA DE LA CÉLULA - GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1520000   ', '5200 PUERTAS DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1520100   ', '5201 PUERTAS - GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1520101   ', 'APERTURA DE PUERTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1520102   ', 'APERTURA/PÉRDIDA DE PUERTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1520170   ', 'SISTEMA DE AVISO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1530000   ', '5300 ESTRUCTURA DEL FUSELAJE DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1530100   ', '5301 FALLO DE LA CÉLULA - OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1530200   ', '5302 DESINTEGRACIÓN DE LA CÉLULA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1540000   ', '5400 ESTRUCTURA DE LA BARQUILLA/SOPORTE DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1550000   ', '5500 ESTRUCTURA DEL EMPENAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1552000   ', '5520 TIMÓN DE PROFUNDIDAD DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1554000   ', '5540 TIMÓN DE DIRECCIÓN DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1560000   ', '5600 VENTANAS/PARABRISAS DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1560100   ', '5601 VENTANAS DE LA AERONAVE EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1560101   ', 'APERTURA/PÉRDIDA DE VENTANA EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1561000   ', '5610 VENTANA DEL COMPARTIMIENTO DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1570000   ', '5700 ESTRUCTURA DEL ALA DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1610000   ', '6100 HÉLICES EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1610100   ', '6101 HÉLICES DE LA AERONAVE - GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1610101   ', 'SOBREVELOCIDAD DE LA HÉLICE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1610102   ', 'PÉRDIDA DE LA HÉLICE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1610120   ', 'CONTROL DE LA HÉLICE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1620000   ', '6200 SISTEMA DEL ROTOR PRINCIPAL DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1620100   ', '6201 ROTOR PRINCIPAL - GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1620101   ', 'BATIMIENTO DE LA PALA DEL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1630000   ', '6300 SISTEMA DE IMPULSIÓN DEL ROTOR PRINCIPAL');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1630100   ', '6301 EJE PROPULSOR DEL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1632000   ', '6320 TRANSMISIÓN DEL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1632001   ', 'DETECTOR DE VIRUTAS DE LA CAJA DE LA TRANSMISIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1640000   ', '6400 SISTEMA DEL ROTOR DE COLA DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1650000   ', '6500 SISTEMA DE IMPULSIÓN DEL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1651000   ', '6510 EJE PROPULSOR DEL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1652000   ', '6520 CAJA DE LA TRANSMISIÓN (90 GRADOS) DEL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1653000   ', '6530 CAJA DE LA TRANSMISIÓN DEL ROTOR DE COLA (45 GRADOS)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1670000   ', '6700 SISTEMA DE MANDOS DE VUELO DE UNA AERONAVE (ROTORA)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1710000   ', '7100 CONJUNTO DEL SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720000   ', '7200 MOTOR DE TURBINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720100   ', '7201 MOTOR DE TURBINA - EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720101   ', 'MOTOR DE TURBINA - DESPRENDIMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720102   ', 'MOTOR DE TURBINA - FALLO NO CONTENIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720103   ', 'MOTOR DE TURBINA - FALLO MECÁNICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720104   ', 'MOTOR DE TURBINA - FALLO NO MECÁNICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720105   ', 'MOTOR DE TURBINA - FALLO SIMULADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720106   ', 'MOTOR DE TURBINA - FALTA DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720107   ', 'MOTOR DE TURBINA - EMPUJE ASIMÉTRICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720108   ', 'MOTOR DE TURBINA - FALLOS MÚLTIPLES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720109   ', 'MOTOR DE TURBINA - VIBRACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720110   ', 'MOTOR DE TURBINA - CAJA DE LA TRANSMISIÓN DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1720113   ', 'MOTOR DE TURBINA - DETECCIÓN DE VIRUTAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1730000   ', '7300 SISTEMA DE COMBUSTIBLE Y CONTROL DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1740000   ', '7400 SISTEMA DE ENCENDIDO DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1750000   ', '7500 SISTEMA DE AIRE DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1760000   ', '7600 MANDOS DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1770000   ', '7700 SISTEMA DE INDICACIÓN DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1780000   ', '7800 SISTEMA DE ESCAPE DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1783000   ', '7830 SISTEMA INVERSOR DEL EMPUJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1790000   ', '7900 SISTEMA DE ACEITE DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1800000   ', '8000 SISTEMA DE ARRANQUE DEL MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1810000   ', '8100 SISTEMA DE ESCAPE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1820000   ', '8200 SISTEMA DE INYECCIÓN DE AGUA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1830000   ', '8300 CAJA DE TRANSMISIÓN AUXILIAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850000   ', '8500 MOTOR ALTERNATIVO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850100   ', '8501 MOTOR ALTERNATIVO EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850101   ', 'MOTOR ALTERNATIVO - DESPRENDIMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850102   ', 'MOTOR ALTERNATIVO - FALLO NO CONTENIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850103   ', 'MOTOR ALTERNATIVO - FALLO MECÁNICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850104   ', 'MOTOR ALTERNATIVO - FALLO NO MECÁNICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850105   ', 'MOTOR ALTERNATIVO - FALLO SIMULADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850106   ', 'MOTOR ALTERNATIVO - FALTA DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850107   ', 'MOTOR ALTERNATIVO - FORMACIÓN DE HIELO EN EL CARBURADOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850108   ', 'MOTOR ALTERNATIVO - FALLOS MÚLTIPLES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850109   ', 'MOTOR ALTERNATIVO - FALLO DE LA CAJA DE LA TRANSMISIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1850110   ', 'MOTOR ALTERNATIVO - VIBRACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990000   ', 'EVENTOS DE COMPONENTES NO ESPECIFICADOS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990100   ', 'EXPLOSIONES/INCENDIO/VAPORES/GASES/HUMO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990101   ', 'EXPLOSIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990102   ', 'EXPLOSIÓN - CABINA DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990103   ', 'EXPLOSIÓN - CABINA DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990104   ', 'EXPLOSIÓN - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990105   ', 'EXPLOSIÓN - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990106   ', 'EXPLOSIÓN - LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990107   ', 'EXPLOSIÓN - COMPARTIMENTO DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990108   ', 'EXPLOSIÓN - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990109   ', 'EXPLOSIÓN - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990110   ', 'EXPLOSIÓN - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990111   ', 'INCENDIO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990112   ', 'INCENDIO - CABINA DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990113   ', 'INCENDIO - CABINA DE PASAJEROS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990114   ', 'INCENDIO - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990115   ', 'INCENDIO - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990116   ', 'INCENDIO - LAVABO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990117   ', 'INCENDIO - COMPARTIMENTO DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990118   ', 'INCENDIO - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990119   ', 'INCENDIO - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990120   ', 'INCENDIO - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990121   ', 'VAPORES/GASES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990122   ', 'VAPORES/GASES - CABINA DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990123   ', 'VAPORES/GASES - CABINA DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990124   ', 'VAPORES/GASES - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990125   ', 'VAPORES/GASES - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990126   ', 'VAPORES/GASES - LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990127   ', 'VAPORES/GASES - COMPARTIMENTO DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990128   ', 'VAPORES/GASES - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990129   ', 'VAPORES/GASES - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990130   ', 'VAPORES/GASES - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990131   ', 'HUMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990132   ', 'HUMO - CABINA DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990133   ', 'HUMO - CABINA DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990134   ', 'HUMO - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990135   ', 'HUMO - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990136   ', 'HUMO - LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990137   ', 'HUMO - ÁREA DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990138   ', 'HUMO - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990139   ', 'HUMO - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990140   ', 'HUMO - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990141   ', 'OLOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990142   ', 'OLOR - PUESTO DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990143   ', 'OLOR - CABINA DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990144   ', 'OLOR - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990145   ', 'OLOR - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990146   ', 'OLOR - LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990147   ', 'OLOR - COMPARTIMENTO DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990148   ', 'OLOR - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990149   ', 'OLOR - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990150   ', 'OLOR - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990151   ', 'OLOR ELÉCTRICO');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990152   ', 'OLOR ELÉCTRICO - PUESTO DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990153   ', 'OLOR ELÉCTRICO - CABINA DE PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990154   ', 'OLOR ELÉCTRICO - BODEGA/BARQUILLA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990155   ', 'OLOR ELÉCTRICO - COCINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990156   ', 'OLOR ELÉCTRICO - LAVABOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990157   ', 'OLOR ELÉCTRICO - COMPARTIMENTO DE AVIÓNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990158   ', 'OLOR ELÉCTRICO - SISTEMA MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990159   ', 'OLOR ELÉCTRICO - APU');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990160   ', 'OLOR ELÉCTRICO - OTRA UBICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990161   ', 'INCENDIO - TREN DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990162   ', 'HUMO - TREN DE ATERRIZAJE:');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990200   ', 'VIBRACIÓN/TRAQUETEO/RUIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990201   ', 'RUIDO/TRAQUETEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990202   ', 'VIBRACIÓN/SACUDIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('1990203   ', 'OBJETO SUELTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2000000   ', 'OPERACIÓN GENERAL DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010000   ', 'MANEJO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010100   ', 'RELACIONADO CON LA ALTITUD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010102   ', 'PROXIMIDAD EXCESIVA AL TERRENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010103   ', 'OTRO EVENTO DE ALTITUD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010200   ', 'MANIOBRA BRUSCA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010201   ', 'ENTORNO - MANIOBRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010202   ', 'TRIPULACIÓN - MANIOBRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010203   ', 'OTRA MANIOBRA BRUSCA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010300   ', 'CONTACTO DEL ALA/BARQUILLA DE CARGA/FLOTADOR CON EL SUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010400   ', 'DESACUERDO ENTRE SISTEMAS Y TRIPULACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010500   ', 'VIRAJE BRUSCO AL DESPEGAR/ATERRIZAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010501   ', 'VIRAJE BRUSCO INTENCIONADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010502   ', 'VIRAJE BRUSCO INVOLUNTARIO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010600   ', 'ATERRIZAJE DURO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010700   ', 'ATERRIZAJE JUNTO A LA SUPERFICIE DE ATERRIZAJE ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010800   ', 'ATERRIZAJE DEMASIADO CORTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2010900   ', 'ROTACIÓN EXCESIVA - ROCE/GOLPE CON LA COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011000   ', 'APROXIMACIÓN DESESTABILIZADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011200   ', 'ATERRIZAJE SIN TREN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011201   ', 'ATERRIZAJE SIN TREN - INTENCIONADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011202   ', 'ATERRIZAJE SIN TREN - NO INTENCIONADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011203   ', 'ATERRIZAJE SIN TREN - CAUSA DESCONOCIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011300   ', 'AMARAJE CON TREN EXTENDIDO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011400   ', 'ATERRIZAJE LARGO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011500   ', 'ATERRIZAJE RÁPIDO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2011600   ', 'DESCENSO INSEGURO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020000   ', 'TRIPULACIÓN DE VUELO/ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020100   ', 'CONFLICTO DE TRÁFICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020300   ', 'COMUNICACIONES PILOTO/ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020400   ', 'INFRACCIÓN DEL ESPACIO AÉREO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020500   ', 'DESVIACIÓN - AUTORIZACIÓN ATC');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020501   ', 'DESVIACIÓN - PUESTA EN MARCHA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020502   ', 'DESVIACIÓN - RETROCESO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020503   ', 'DESVIACIÓN - RODAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020504   ', 'DESVIACIÓN - ALINEACIÓN EN PISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020505   ', 'DESVIACIÓN - DESPEGUE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020506   ', 'DESVIACIÓN - EN RUTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020507   ', 'DESVIACIÓN - OCEÁNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020508   ', 'DESVIACIÓN - APROXIMACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020509   ', 'DESVIACIÓN - ESPERA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020510   ', 'DESVIACIÓN - ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020511   ', 'DESVIACIÓN - CRUCE DE PISTA DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020512   ', 'DESVIACIÓN - LÍMITE DE AUTORIZACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020513   ', 'DESVIACIÓN - PROCEDIMIENTO ESPECIAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020514   ', 'DESVIACIÓN - APROXIMACIÓN FRUSTRADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020515   ', 'DESVIACIÓN - APROXIMACIÓN BAJA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020516   ', 'DESVIACIÓN - TOMA Y DESPEGUE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020517   ', 'DESVIACIÓN - NIVEL/ALTITUD DE VUELO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020518   ', 'DESVIACIÓN - DETALLES ASIGNADOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020519   ', 'DESVIACIÓN - VELOCIDAD ESPECÍFICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020520   ', 'DESVIACIÓN - RESTRICCIÓN DE TIEMPO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020521   ', 'DESVIACIÓN - ASCENSO/DESCENSO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020522   ', 'DESVIACIÓN - ASCENSO/DESCENSO - AUTORIZACIÓN CONDICIONAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020523   ', 'DESVIACIÓN - MANTENER CORTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020524   ', 'DESVIACIÓN - PROCEDIMIENTO DE ATENUACIÓN DEL RUIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020700   ', 'DESVIACIÓN - REGULACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020702   ', 'DESVIACIONES - EQUIPO ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020703   ', 'OTRA DESVIACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020800   ', 'DESVIACIÓN DE LA TRIPULACIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020801   ', 'MSA EN RUTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020802   ', 'MÍNIMOS DE ATERRIZAJE ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020803   ', 'ATM SID');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020804   ', 'ATM STAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020805   ', 'PROCEDIMIENTO DE APROXIMACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020806   ', 'RESTRICCIÓN DE VELOCIDAD ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2020900   ', 'OTRO PROCEDIMIENTO ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030000   ', 'SEGURIDAD EN CABINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030100   ', 'SALIDA BLOQUEADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030200   ', 'CINTURÓN DE SEGURIDAD INSERVIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030300   ', 'FALLO DE RAMPA O RAMPA NO ARMADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030400   ', 'TRIPULACIÓN DE CABINA - MÉDICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030500   ', 'TRIPULACIÓN DE CABINA - LESIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030600   ', 'TRIPULACIÓN DE CABINA - OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030700   ', 'CABINA - COMUNICACIONES CON LA CABINA DE PILOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030800   ', 'EMERGENCIA MÉDICA - PASAJERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2030900   ', 'EQUIPAJE DE MANO DEL PASAJERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2031000   ', 'ANIMALES EN LA CABINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2031100   ', 'APERTURA DE PUERTA/INTERFERENCIA CON LA PUERTA - PASAJEROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2039800   ', 'OTRO EVENTO RELACIONADO CON LA SEGURIDAD DE CABINA NO OCASIONADO POR LA TRIPULACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2040000   ', 'TRIPULACIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2040100   ', 'INCAPACITACIÓN/ENFERMEDAD/PROBLEMA MÉDICO DE LA TRIPULACIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050000   ', 'COLISIÓN DE AERONAVE CON OBSTÁCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050100   ', 'COLISIÓN DE AERONAVE - AERONAVE EN MOVIMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050101   ', 'COLISIÓN DE AERONAVE - AMBAS AERONAVES EN VUELO');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050102   ', 'COLISIÓN DE AERONAVE - UNA AERONAVE EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050103   ', 'COLISIÓN DE AERONAVE - AMBAS AERONAVES EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050104   ', 'COLISIÓN DE UNA AERONAVE CON GLOBO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050105   ', 'COLISIÓN DE AERONAVE - ULTRALIGERA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050106   ', 'COLISIÓN DE AERONAVE - DIRIGIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050200   ', 'COLISIÓN DE AERONAVE - TERRENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050201   ', 'COLISIÓN DE AERONAVE - TERRENO NIVELADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050202   ', 'COLISIÓN DE AERONAVE - TERRENO ELEVADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050300   ', 'COLISIÓN DE AERONAVE - OBJETO EN ALTURA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050301   ', 'CHOQUE DE CON AVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050302   ', 'COLISIÓN DE AERONAVE - AERONAVE DE AEROMODELISMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050303   ', 'COLISIÓN DE AERONAVE - OTRO OBJETO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050304   ', 'COLISIÓN DE AERONAVE - PARACAIDISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050400   ', 'COLISIÓN DE AERONAVE - OBJETO EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050401   ', 'COLISIÓN DE AERONAVE - ESTRUCTURA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050402   ', 'COLISIÓN DE AERONAVE - ANIMAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050403   ', 'COLISIÓN DE AERONAVE - LUCES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050404   ', 'COLISIÓN DE AERONAVE - EDIFICIO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050405   ', 'COLISIÓN DE AERONAVE - TRONCO SUMERGIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050406   ', 'COLISIÓN DE AERONAVE - LA ORILLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050407   ', 'COLISIÓN DE AERONAVE - OTRO OBJETO 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050408   ', 'COLISIÓN DE AERONAVE - AERONAVE ESTACIONADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050410   ', 'COLISIÓN DE AERONAVE - PERSONA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050411   ', 'COLISIÓN DE AERONAVE - CABLE/LÍNEA ELÉCTRICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050412   ', 'COLISIÓN DE AERONAVE - BANCO DE NIEVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050413   ', 'COLISIÓN DE AERONAVE - ESTRUCTURA ALTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050414   ', 'COLISIÓN DE AERONAVE - ÁRBOL/VEGETACIÓN ALTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050415   ', 'COLISIÓN DE AERONAVE - VEHÍCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2050416   ', 'COLISIÓN DE AERONAVE - OLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060000   ', 'DAÑOS A LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060100   ', 'DESCOMPRESIÓN EXPLOSIVA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060200   ', 'DAÑOS POR OBJETO EXTRAÑO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060300   ', 'DAÑOS POR RESONANCIA EN TIERRA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060500   ', 'DAÑOS A LA AERONAVE POR SOBREFATIGA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060600   ', 'HÉLICE/ROTOR/CHORRO DE REACTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060700   ', 'HUNDIMIENTO A TRAVÉS DE SUPERFICIE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2060800   ', 'DAÑOS POR OBJETO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2061300   ', 'AERONAVE HUNDIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2061500   ', 'GOLPE AL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2070000   ', 'SALIDA DE LA AERONAVE DEL AREA DE MOVIMIENTOS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2070100   ', 'SALIDA LATERAL DE PISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2070200   ', 'SALIDA DE LA CALLE DE RODAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2070300   ', 'SALIDA DE LA RAMPA/PLATAFORMA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2070400   ', 'SALIDA POR EL FINAL DE PISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080000   ', 'AVIÓN - DESVIACIONES DE LA TRAYECTORIA DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080100   ', 'AVIÓN - DESVIACIÓN DE LA ALTITUD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080200   ', 'AVIÓN - DESVIACIÓN DEL RUMBO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080300   ', 'AVIÓN - PERTURBACIÓN/PÉRDIDA DE SUSTENTACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080400   ', 'AVIÓN - BARRENA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080500   ', 'AVIÓN -  PICADO EN ESPIRAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080600   ', 'AVIÓN - DESVIACIÓN DE LA ACTITUD DE CABECEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080700   ', 'AVIÓN - DESVIACIÓN DE LA ACTITUD DE ALABEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080800   ', 'AVIÓN - DELFINEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2080900   ', 'AVIÓN - OTRA DESVIACIÓN DE LA TRAYECTORIA DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090000   ', 'DESVIACIÓN DE LA TRAYECTORIA DE VUELO DE HELICÓPTERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090100   ', 'HELICÓPTERO - DESVIACIÓN DE LA ALTITUD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090200   ', 'HELICÓPTERO - DESVIACIÓN DEL RUMBO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090300   ', 'HELICÓPTERO  - DESVIACIÓN DE LA ACTITUD DE CABECEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090400   ', 'HELICÓPTERO - DESVIACIÓN DE LA ACTITUD DE ALABEO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090500   ', 'HELICÓPTERO - VUELCO DINÁMICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090600   ', 'HELICÓPTERO - REVOLUCIONES INADECUADAS DEL ROTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090700   ', 'HELICÓPTERO - HUNDIMIENTO CON POTENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090800   ', 'HELICÓPTERO - GUIÑADA NO CONTROLADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2090900   ', 'HELICÓPTERO - OTRA DESVIACIÓN DE LA TRAYECTORIA DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120000   ', 'PREPARACIÓN DEL VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120100   ', 'CARGA INCORRECTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120200   ', 'CENTRADO DE COMBUSTIBLE INCORRECTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120300   ', 'INFRACCIÓN DEL EQUIPO MÍNIMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120400   ', 'SOBREPESO/CENTRO DE GRAVEDAD (COG) INCORRECTO AL DESPEGUE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2120500   ', 'DESPEGUE CON DAÑOS ANTERIORES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2130000   ', 'ASISTENCIA A LA AERONAVE EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2140000   ', 'INGESTIÓN DE OBJETOS EXTRAÑOS - MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2140100   ', 'TURBINA - AVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2140200   ', 'AGUA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2140300   ', 'HIELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2140400   ', 'OTROS ELEMENTOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150000   ', 'LESIONES A PERSONAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150100   ', 'LESIONES DEBIDAS A TURBULENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150200   ', 'LESIONES - MANIOBRA BRUSCA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150300   ', 'LESIONES - CHORRO DE HÉLICE/REACTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150400   ', 'LESIONES - COMPONENTE DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2150500   ', 'LESIONES DE OTRAS FUENTES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160000   ', 'CAÍDA DE MATERIAL DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160100   ', 'HIELO 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160101   ', 'HIELO (METEOROLOGÍA)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160102   ', 'HIELO (TUBOS DE DRENAJE DE LA COCINA)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160103   ', 'HIELO (AGUA DEL ASEO)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160104   ', 'HIELO (AGUA POTABLE)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160105   ', 'HILO (SIN DETERMINAR)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160200   ', 'OBJETOS (NO HIELO)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160201   ', 'PANELES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160202   ', 'COMPONENTE IDENTIFICADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160203   ', 'COMPONENTE SIN IDENTIFICAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2160300   ', 'AVISTAMIENTO - OBJETO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170000   ', 'NAVEGACIÓN DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170100   ', 'SELECCIÓN DE AERÓDROMO EQUIVOCADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170200   ', 'SELECCIÓN DE PISTA DE ATERRIZAJE EQUIVOCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170300   ', 'SELECCIÓN DE CALLE DE RODAJE EQUIVOCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170400   ', 'ERROR DE NAVEGACIÓN - DERROTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2170500   ', 'ERROR DE NAVEGACIÓN - OTROS');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180000   ', 'AERONAVE - SEPARACIÓN OBJETO/TERRENO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180100   ', 'CUASI COLISIONES - PÉRDIDA DE SEPARACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180101   ', 'PÉRDIDA DE SEPARACIÓN - AERONAVE, AMBAS EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180102   ', 'PÉRDIDA DE SEPARACIÓN - UNA AERONAVE EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180103   ', 'PÉRDIDA DE SEPARACIÓN - AMBAS AERONAVES EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180104   ', 'PÉRDIDA DE SEPARACIÓN - COLISIÓN POTENCIAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180105   ', 'PÉRDIDA DE SEPARACIÓN SIN RIESGO DE COLISIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180106   ', 'PÉRDIDA DE SEPARACIÓN RIESGO SIN DETERMINAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180107   ', 'INFRACCIÓN DE MÍNIMOS DE SEPARACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180200   ', 'CUASI COLISIÓN CON TERRENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180201   ', 'CUASI COLISIÓN CON TERRENO NIVELADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180202   ', 'CUASI COLISIÓN - TERRENO ELEVADO/MONTAÑA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180300   ', 'CUASI COLISIÓN CON OBJETO EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180301   ', 'CUASI COLISIÓN - AVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180302   ', 'CUASI COLISIÓN - OTRO OBJETO EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180303   ', 'CUASI COLISIÓN - OBJETO EN VUELO DESCONOCIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180304   ', 'CUASI COLISIÓN CON PARACAIDISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180400   ', 'CUASI COLISIÓN - OBJETO EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180401   ', 'CUASI COLISIÓN - AERONAVE ESTACIONADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180402   ', 'CUASI COLISIÓN CON OBJETO ALTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180403   ', 'CUASI COLISIÓN - CON PERSONA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180405   ', 'CUASI COLISIÓN - VEHÍCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2180406   ', 'CUASI COLISIÓN - OTRO OBJETO EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200000   ', 'INCURSIONES EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200100   ', 'INCURSIONES EN PISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200101   ', 'POR UNA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200102   ', 'POR UN VEHÍCULO/EQUIPO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200103   ', 'POR UNA PERSONA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200104   ', 'POR UN ANIMAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200200   ', 'INCURSIÓN EN CALLE DE RODADURA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200201   ', 'POR UNA AERONAVE 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200202   ', 'POR UN VEHÍCULO/EQUIPO 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200203   ', 'POR UNA PERSONA 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200204   ', 'POR UN ANIMAL 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200300   ', 'INCURSIÓN EN PLATAFORMA/RAMPA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200301   ', 'POR UNA AERONAVE 3');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200302   ', 'POR UN VEHÍCULO/EQUIPO 3');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200303   ', 'POR UNA PERSONA 3');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2200304   ', 'POR UN ANIMAL 3');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220000   ', 'ENCUENTROS METEOROLÓGICOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220100   ', 'CONDICIONES DE ENGELAMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220200   ', 'CIZALLADURA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220300   ', 'CENIZA VOLCÁNICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220400   ', 'ESTELA TURBULENTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220500   ', 'IMC');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220600   ', 'TURBULENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220700   ', 'METEOROLOGÍA INESPERADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220800   ', 'VIENTO CRUZADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2220900   ', 'VIENTO EN COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2221000   ', 'PÉRDIDA DE REFERENCIA VISUAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2221100   ', 'ENCUENTRO CON VIENTO EN CARA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2221200   ', 'VIENTO FUERTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2221300   ', 'ENCUENTRO CON GRANIZO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2221400   ', 'CONDICIÓN DE NUBOSIDAD ADVERSA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2222000   ', 'IMPACTO DE RAYO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230000   ', 'SEGURIDAD EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230100   ', 'AVISO/AMENAZA DE BOMBA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230200   ', 'SECUESTRO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230300   ', 'SABOTAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230400   ', 'INTERVENCIÓN MILITAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230500   ', 'PASAJERO DIFÍCIL/INDISCIPLINADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230600   ', 'POLIZÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230700   ', 'AMENAZAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2230800   ', 'DAÑOS EN LA AERONAVE PROVOCADOS POR ACTO ILÍCITO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240000   ', 'EVENTOS ESPECÍFICOS DE ULTRALIGERO/VELERO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240100   ', 'EVENTO RELACIONADO CON EL EQUIPO DE LANZAMIENTO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240101   ', 'ABORTO DE DESPEGUE ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240104   ', 'DESCONEXIÓN DE SOGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240198   ', 'OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240200   ', 'REMOLCADO DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240201   ', 'FALLO DE AERONAVE REMOLCADORA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240202   ', 'SUBIDA POR ENCIMA DE LA AERONAVE REMOLCADORA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240203   ', 'FALLO DE SOGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240204   ', 'DESCONEXIÓN DE SOGA 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240205   ', 'REMOLCADO AÉREO - OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240300   ', 'PÉRDIDA DE SUSTENTACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240301   ', 'PÉRDIDA DE SUSTENTACIÓN - TÉRMICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240302   ', 'PÉRDIDA DE SUSTENTACIÓN - ONDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2240303   ', 'PÉRDIDA DE SUSTENTACIÓN - PENDIENTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250000   ', 'EVENTOS ESPECÍFICOS DE GLOBOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250100   ', 'ESTRUCTURA ENVOLVENTE QUEMADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250101   ', 'FALDÓN QUEMADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250102   ', 'PANELES QUEMADOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250200   ', 'ESTRUCTURA ENVOLVENTE DESGARRADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250300   ', 'BARQUILLA VOLCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250400   ', 'BARQUILLA ATRAPADA EN OBSTÁCULOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2250500   ', 'DESLIZAMIENTO DE BARQUILLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260000   ', 'ACTIVACIÓN DE UN SISTEMA DE AVISO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260100   ', 'ACTIVACIÓN DE ACAS/TCAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260200   ', 'AVISO DE CONFIGURACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260300   ', 'AVISO DE PROXIMIDAD CON EL TERRENO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260400   ', 'AVISO DEL SISTEMA DE VIGILANCIA DE SALUD ESTRUCTURAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260500   ', 'ACTIVACIÓN DE AVISO DE ENTRADA EN PÉRDIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2260600   ', 'ACTIVACIÓN DE OTRO SISTEMA DE AVISO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270000   ', 'INTERFERENCIA CON AERONAVE DESDE TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270100   ', 'INTERFERENCIA POR LASER/EMISOR DE HACES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270200   ', 'INTERFERENCIAS POR FUEGOS ARTIFICIALES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270300   ', 'INTERFERENCIA POR LUCES DE BÚSQUEDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270400   ', 'INTERFERENCIA POR COMETAS EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270500   ', 'INTERFERENCIA POR ACTIVIDAD DE AEROMODELISMO');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270600   ', 'INTERFERENCIA POR GLOBOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('2270700   ', 'INTERFERENCIA POR OTRA ACTIVIDAD EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3000000   ', 'CONSECUENCIAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3010000   ', 'ATERRIZAJE DE PRECAUCIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3020000   ', 'DECLARACIÓN DE EMERGENCIA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3020100   ', 'DECLARACIÓN DE EMERGENCIA - MAYDAY');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3020200   ', 'DECLARACIÓN DE EMERGENCIA - LLAMADA PAN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3030000   ', 'ABORTO DE DESPEGUE 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3030100   ', 'ABORTO DE DESPEGUE A ALTA VELOCIDAD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3030200   ', 'ABORTO DE DESPEGUE A BAJA VELOCIDAD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3040000   ', 'ATERRIZAJE FRUSTRADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3050000   ', 'APROXIMACIÓN FRUSTRADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3060000   ', 'DESCENSO DE EMERGENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3070000   ', 'AMERIZAJE FORZOSO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3080000   ', 'ATERRIZAJE FORZOSO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3090000   ', 'APROXIMACIÓN POR DEBAJO DE MÍNIMOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3100000   ', 'SUELTA DE COMBUSTIBLE EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3110000   ', 'EVACUACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3120000   ', 'ATERRIZAJE SIN FLAPS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3130000   ', 'ESPERA PARA CONSUMO DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3140000   ', 'RETORNO DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3150000   ', 'ATERRIZAJE CON SOBREPESO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3160000   ', 'AERONAVE ABANDONADA/LA TRIPULACIÓN EYECTÓ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3170000   ', 'SUELTA DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3180000   ', 'EMERGENCIA CANCELADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3190000   ', 'CANCELACIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3200000   ', 'RETRASO DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3210000   ', 'INSPECCIÓN EN SOBREVUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3220000   ', 'VERIFICACIÓN DE MANEJO DE LA AERONAVE    ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3230000   ', 'DESCENSO PREVENTIVO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3240000   ', 'CARGA EXTERNA SOLTADA/ARROJADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3250000   ', 'DESVÍO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3250100   ', 'DESVÍO - METEOROLÓGICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3250200   ', 'DESVÍO - RAZONES TÉCNICAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3250300   ', 'DESVÍO - DECISIÓN OPERATIVA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3250400   ', 'DESVÍO - OTRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3260000   ', 'CAMBIO DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3270000   ', 'AUTORROTACIÓN DE EMERGENCIA (HELICÓPTERO)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3280000   ', 'PARADA/APAGADO DE MOTOR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3280100   ', 'PARADA DE MOTOR - PREVENTIVA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3280200   ', 'PARADA DE MOTOR - NO COMANDADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3290000   ', 'PICADO/VOLCADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('3300000   ', 'MOVIMIENTO DE LA AERONAVE NO ORDENADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4000000   ', 'SERVICIOS DE NAVEGACIÓN AÉREA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010000   ', 'CUESTIONES OPERACIONALES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010100   ', 'COMUNICACIONES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010200   ', 'PROVISIÓN DE INFORMACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010201   ', 'PROVISIÓN DE INFORMACIÓN DE VUELO ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010202   ', 'PROVISIÓN DE INFORMACIÓN GEOGRÁFICA ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010203   ', 'PROVISIÓN DE INFORMACIÓN METEOROLÓGICA ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010204   ', 'PROVISIÓN DE INFORMACIÓN DE TRÁFICO ANS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010300   ', 'PROVISIÓN DE SEPARACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010400   ', 'DETECCIÓN/RESOLUCIÓN DE CONFLICTOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010500   ', 'MANEJO DE SUCESOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010600   ', 'CAMBIO DE TURNO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010700   ', 'RELACIONADO CON LA AUTORIZACIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010701   ', 'AUTORIZACIÓN  - ALTITUD EQUIVOCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010702   ', 'AUTORIZACIÓN  -  RUMBO EQUIVOCADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010703   ', 'AUTORIZACIÓN  -  VELOCIDAD EQUIVOCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4010704   ', 'AUTORIZACIÓN  -  AERONAVE EQUIVOCADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4020000   ', 'SERVICIO DE INFORMACIÓN AERONÁUTICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4020100   ', 'INFORMACIÓN DESACTUALIZADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4020200   ', 'DIFERENCIA DE DATOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4020300   ', 'DATOS ERRÓNEOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4020400   ', 'TRIPULACIÓN DE VUELO Y DATOS ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4030000   ', 'ATFM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4040000   ', 'GESTIÓN DEL ESPACIO AÉREO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050000   ', 'FUNCIONAMIENTO ATM/CNS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050100   ', 'FALLO DE ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050101   ', 'FALLO DE SERVICIOS DE TRÁNSITO AÉREO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050102   ', 'FALLO ASM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050103   ', 'FALLO ATFM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050200   ', 'FALLO DE COMUNICACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050300   ', 'FALLO DE VIGILANCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050400   ', 'FALLO DE PROCESAMIENTO DE DATOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050500   ', 'FALLO DE LA INFORMACIÓN DE APOYO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050600   ', 'FALLO EN PROPORCIONAR NAVEGACIÓN AÉREA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4050700   ', 'FALLO - FUENTE DE ENERGÍA ELÉCTRICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060000   ', 'SITUACIÓN DE EMERGENCIA ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060100   ', 'INCENDIO - INSTALACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060200   ', 'INTERFERENCIA ILÍCITA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060300   ', 'AMENAZA DE BOMBA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060400   ', 'HUMO - INSTALACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060500   ', 'SABOTAJE - INSTALACIÓN ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4060600   ', 'OTRO EVENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4070000   ', 'EVENTO QUE AFECTAN AL ATM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4070100   ', 'CIERRE DE FIR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4070200   ', 'CIERRE DE AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4070300   ', 'CIERRE DE PISTA DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('4070400   ', 'CAPACIDAD REDUCIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5000000   ', 'AERÓDROMO Y AYUDAS TERRESTRES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010000   ', 'AYUDAS TERRESTRES EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010100   ', 'SISTEMAS DE APROXIMACIÓN AL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010101   ', 'SISTEMA DE ATERRIZAJE POR INSTRUMENTOS (ILS)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010102   ', 'SISTEMA DE POSICIONAMIENTO GLOBAL (GPS)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010103   ', 'RADIOBALIZA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010104   ', 'FARO NO DIRECCIONAL (NDB)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010105   ', 'EQUIPO DE MEDICIÓN DE DISTANCIA (DME)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010106   ', 'RADIOFARO OMNIDIRECCIONAL VHF (VOR)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010107   ', 'INDICADOR DE TRAYECTORIA DE APROXIMACIÓN DE PRECISIÓN (PAPI)');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010108   ', 'SISTEMAS DE ATERRIZAJE POR MICROONDAS (MLS)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010109   ', 'RADAR DE APROXIMACIÓN DE PRECISIÓN (PAR)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5010110   ', 'INDICADOR VISUAL DE PENDIENTE DE APROXIMACIÓN (VASI)');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020000   ', 'SISTEMAS DE AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020100   ', 'ILUMINACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020101   ', 'ILUMINACIÓN DE APROXIMACIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020102   ', 'ILUMINACIÓN DE LA PISTA DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020103   ', 'ILUMINACIÓN DE LA CALLE DE RODADURA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020104   ', 'ILUMINACIÓN DE LA PLATAFORMA ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020200   ', 'ENERGÍA DE EMERGENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020300   ', 'SEÑALES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020400   ', 'SEÑALIZACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020401   ', 'SEÑALIZACIÓN DE PISTA DE ATERRIZAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020402   ', 'SEÑALIZACIÓN DE LA CALLE DE RODAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020403   ', 'SEÑALIZACIÓN DE LA PLATAFORMA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020404   ', 'SEÑALIZACIÓN DE OBSTÁCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020500   ', 'EQUIPO DE CAPTURA DE SALIDA DE PISTA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020600   ', 'OTRO EQUIPO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020700   ', 'EQUIPO DE LANZAMIENTO CON CABESTRANTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020701   ', 'FALLO DEL CABESTRANTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020702   ', 'ROTURA DEL CABLE DE LANZAMIENTO CON CABESTRANTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020798   ', 'OTRO EVENTO RELACIONADO CON EL EQUIPO DE LANZAMIENTO CON CABESTRANTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5020800   ', 'SISTEMA DE ENERGÍA PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030000   ', 'SERVICIOS / OPERACIONES DEL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030100   ', 'GESTIÓN DE LA PLATAFORMA/RAMPA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030200   ', 'RETIRADA DE NIEVE/HIELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030300   ', 'MANTENIMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030400   ', 'CONTROL DE OBJETOS EXTRAÑOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030500   ', 'CONTROL DE AVES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030600   ', 'CONTROL DE FAUNA SALVAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030700   ', 'OPERACIONES DE VEHÍCULO/EQUIPO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030701   ', 'VEHÍCULO - COLISIÓN CON VEHÍCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030702   ', 'VEHÍCULO - COLISIÓN CON PERSONA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030703   ', 'VEHÍCULO - COLISIÓN CON OBJETO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5030704   ', 'AERONAVE GOLPEADA/DAÑADA POR VEHÍCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5040000   ', 'FUNCIONAMIENTO/DISTRIBUCIÓN EN GENERAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5040100   ', 'DISTRIBUCIÓN DEL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5040200   ', 'FUNCIONAMIENTO DEL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050000   ', 'SERVICIOS DE ASISTENCIA EN TIERRA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050100   ', 'MANTENIMIENTO EN LÍNEA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050200   ', 'DESHIELO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050300   ', 'CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050301   ', 'CARGA DE EQUIPAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050302   ', 'CARGA DE MERCANCÍAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050303   ', 'CARGA - OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050400   ', 'SERVICIOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050401   ', 'ABASTECIMIENTO DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050402   ', 'CATERING');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050403   ', 'SERVICIO DE FLUIDOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5050404   ', 'SERVICIO - OTROS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060000   ', 'RELACIONADO CON LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060100   ', 'MANIPULACIÓN DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060200   ', 'ACEPTACIÓN DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060300   ', 'PESAJE DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060400   ', 'ETIQUETADO DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060500   ', 'EMBALAJE DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060600   ', 'MOVIMIENTO DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060700   ', 'CARGA/DESCARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060800   ', 'COMPROBACIÓN DE SEGURIDAD DE LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5060900   ', 'ESTIBA DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5070000   ', 'SEGURIDAD DEL AERÓDROMO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5070100   ', 'ENTRADA ILÍCITA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5070200   ', 'SABOTAJE 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('5079800   ', 'OTRO EVENTO RELACIONADO CON LA SEGURIDAD EN EL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('6000000   ', 'EVENTO RELACIONADO CON LA AUTORIDAD DE AVIACIÓN CIVIL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7000000   ', 'EVENTOS DE REGULACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7010000   ', 'RELACIONADO CON EL TIEMPO DE ACTIVIDAD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7010100   ', 'TIEMPO DE ACTIVIDAD SUPERADO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7020000   ', 'TIEMPO DE DESCANSO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7020100   ', 'TIEMPO DE DESCANSO INFERIOR AL REQUERIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7030000   ', 'EVENTO RELACIONADO CON EL PERSONAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7030100   ', 'PERSONAL/TRIPULACIÓN INFERIOR AL REQUERIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7030200   ', 'TRIPULACIÓN/PERSONAL SIN LICENCIA PARA LA ACTIVIDAD');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7040000   ', 'OPERACIÓN INFRINGIENDO LA LICENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7040100   ', 'CERTIFICADO DE OPERADOR DE VUELO (AOC) NO VÁLIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7040200   ', 'LICENCIA ATS NO VÁLIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050000   ', 'EVENTOS DE REGULACIÓN RELACIONADOS CON LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050100   ', 'OPERACIÓN INFRINGIENDO LA MEL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050200   ', 'AERONAVE NO EQUIPADA PARA OPERACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050300   ', 'AERONAVE SIN EQUIPO RVSM');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050400   ', 'AERONAVE NO EQUIPADA/CERTIFICADA PARA APROXIMACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050500   ', 'SUPERADO EL TIEMPO DE FUNCIONAMIENTO/INTERVALO DE MANTENIMIENTO DE LA AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050600   ', 'AERONAVE NO AERONAVEGABLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050601   ', 'DIRECTIVA DE AERONAVEGABILIDAD (AD) SIN IMPLEMENTAR');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7050700   ', 'SIN PERMISO DE VUELO O PERMISO NO VÁLIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('7060000   ', 'OPERACIÓN INFRINGIENDO EL HORARIO DE OPERACIÓN DEL AERÓDROMO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('98000000  ', 'CUALQUIER OTRO EVENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99000000  ', 'DESCONOCIDO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010000  ', 'AERONAVE DESAPARECIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010001  ', 'FALLO DE SOGA 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010002  ', '0700 EVENTO RELACIONADO CON EL LEVANTAMIENTO Y APUNTALAMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010003  ', '0800 EVENTO RELACIONADO CON LA NIVELACIÓN Y PESAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010004  ', '1400 EQUIPO DIVERSO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010005  ', '2560 EQUIPO DE EMERGENCIA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010006  ', '2550 COMPARTIMIENTOS ADICIONALES ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010007  ', '5010 COMPARTIMIENTOS DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010008  ', '5020 SISTEMAS DE CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010009  ', '5030 SISTEMAS RELACIONADOS CON LA CARGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010010  ', '5040 SIN USO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010011  ', '5050 COMPARTIMIENTOS DE ACCESORIOS ');
commit;

insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010012  ', '5060 AISLAMIENTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010013  ', '3110 PANELES DE INSTRUMENTOS Y CONTROL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010014  ', '3120 INSTRUMENTOS INDEPENDIENTES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010015  ', '3140 ORDENADORES CENTRALES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010016  ', '3160 SISTEMAS CENTRALES DE VISUALIZACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010017  ', '3170 SISTEMA DE NOTIFICACIÓN DE DATOS AUTOMÁTICO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010018  ', '3410 DATOS DE AIRE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010019  ', '3450 SISTEMA DEPENDIENTE DE DETERMINACIÓN DE LA POSICIÓN ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010020  ', '4100 SISTEMA DE LASTRE DE AGUA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010021  ', '4200 AVIÓNICA MODULAR INTEGRADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010022  ', '4400 SISTEMAS DE CABINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010023  ', '4500 ORDENADOR CENTRAL DE MANTENIMIENTO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010024  ', '4600 SISTEMAS DE INFORMACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010025  ', '4700 SISTEMA DE GAS INERTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010026  ', '5510 ESTABILIZADOR HORIZONTAL/PLANO DE MORRO HORIZONTAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010027  ', '5530 ESTABILIZADOR VERTICAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010028  ', '5740 BORDE DE ATAQUE DEL ALA Y DISPOSITIVOS DEL BORDE DE ATAQUE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010029  ', '5750 BORDE DE SALIDA DEL ALA/DISPOSITIVOS DEL BORDE DE SALIDA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010030  ', '6600 PALAS/SOPORTES AERODINÁMICOS PLEGABLES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010031  ', 'PLAN DE VUELO INCORRECTO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010032  ', 'AUTORIZACIÓN CANCELADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010033  ', 'ROTACIÓN - RETRASADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010034  ', 'PARADA BRUSCA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010035  ', 'ROTACIÓN - ANTICIPADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010036  ', 'DISCREPANCIA EN EL PLAN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010037  ', 'PLAN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010038  ', 'DISCREPANCIA DEL PLAN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010039  ', 'PLAN DE VUELO 2');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010040  ', 'CARGA EXTERNA DE HELICÓPTERO ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010041  ', 'CARGA EXTERNA - SOLTADA/LIBERADA/LANZADA EN VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010042  ', 'SUELTA INTENCIONADA DE CARGA EXTERNA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010043  ', 'CAÍDA INVOLUNTARIA DE CARGA EXTERNA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010044  ', 'CARGA EXTERNA - CONTACTO CON ESTRUCTURA O COMPONENTE DE AERONAVE ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010045  ', 'CARGA EXTERNA - CONTACTO CON TERRENO/OBJETO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010046  ', 'CARGA EXTERNA APRESADA/ATRAPADA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010047  ', 'CARGA EXTERNA - OSCILACIONES');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010048  ', 'CARGA EXTERNA - OTROS ');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010049  ', 'HELICÓPTERO - SACUDIDA DE MÁSTIL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010050  ', 'COORDINACIÓN');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010051  ', 'ESTACIONAMIENTO DE AERONAVE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010052  ', 'CONTROL DE FAUNA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010053  ', 'ATERRIZAJE CON REBOTE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010054  ', 'DESCARGADOR DE ELECTRICIDAD ESTÁTICA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010055  ', '2150 SISTEMA DE REFRIGERACIÓN DE CABINA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010056  ', '2156 SISTEMA DE REFRIGERACIÓN DE EQUIPOS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010057  ', 'AVISO DE DESCOMPENSACIÓN DE COMBUSTIBLE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010058  ', 'ATERRIZAJE CON MENOS COMBUSTIBLE DE RESERVA QUE EL REQUERIDO POR NORMATIVA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010059  ', 'SUFRIDO POR LA TRIPULACIÓN DE CABINA DURANTE TURBULENCIAS');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010060  ', 'COLISIÓN DE UNA AERONAVE REMOLCADA CON UN OBSTÁCULO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010061  ', 'PÉRDIDA DE EFECTIVIDAD DEL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010062  ', 'OTRO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010063  ', 'CARGA EXTERNA - CAÍDA DE LA ESLINGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010064  ', 'CARGA EXTERNA - CONTACTO CON EL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010065  ', 'CARGA EXTERNA - CONTACTO CON EL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010066  ', 'CUERDA/CABLE EN CONTACTO CON EL ROTOR PRINCIPAL');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010067  ', 'CUERDA/CABLE EN CONTACTO CON EL ROTOR DE COLA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010068  ', 'CUERDA/CABLE EN CONTACTO CON EL FUSELAJE');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010069  ', '3418 SISTEMA DE GESTIÓN DE VUELO');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010070  ', 'LESIONES DURANTE OPERACIONES CON GRÚA O ESLINGA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010071  ', 'MANIOBRA EVASIVA');
insert into TBL_EVENTO_SUCESOS (COD_EVENTO, NOM_EVENTO)
values ('99010072  ', 'AVISO DE BAJO NIVEL DE COMBUSTIBLE');
commit;

insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('02', 'Descenso de Emergencia', 'EMG  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('01', 'Aproximación', 'APR  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('03', 'En Ruta', 'ENR  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('04', 'Ascenso Inicial', 'ICL  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('05', 'Aterrizaje', 'LDG  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('06', 'Maniobras', 'MNV  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('07', 'Mantenimiento', 'MNT  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('08', 'Retroceso/Remolcado', 'PBT  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('09', 'Post-Impacto', 'PIM  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('10', 'En Estacionamiento', 'STD  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('11', 'Despegue', 'TOF  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('12', 'Rodadura', 'TXI  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('13', 'Descenso No Controlado', 'UND  ');
insert into TBL_FASE_VUELO (COD_FASE_VUELO, NOM_FASE_VUELO, ABRE_FASE_VUELO)
values ('14', 'Desconocida', 'UNK  ');
commit;

insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('01', 'PISTA PRINCIPAL');
insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('02', 'CALLE DE RODAJE');
insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('03', 'TERMINAL');
insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('04', 'ELIPUERTO');
insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('05', 'ZONA DE ENGANCHE');
insert into TBL_MOV_PUBLICO (COD_MOV_PUBLICO, NOM_MOV_PUBLICO)
values ('06', 'ZONA DE RECAR. COMBUSTIMBLE');
commit;

insert into TBL_PLATAFORMA (COD_PLATAFORMA, NOM_PLATAFORMA)
values ('01', 'NACIONAL');
insert into TBL_PLATAFORMA (COD_PLATAFORMA, NOM_PLATAFORMA)
values ('02', 'INTERNACIONAL');
insert into TBL_PLATAFORMA (COD_PLATAFORMA, NOM_PLATAFORMA)
values ('03', 'ZONA DE TRANSFERENCIA DE CARGA');
commit;

insert into TBL_PROVEEDOR (COD_PROVEEDOR, NOM_PROVEEDOR)
values ('0001', 'ECOCOPTER');
insert into TBL_PROVEEDOR (COD_PROVEEDOR, NOM_PROVEEDOR)
values ('0002', 'ERICKSON');
insert into TBL_PROVEEDOR (COD_PROVEEDOR, NOM_PROVEEDOR)
values ('0003', 'GHS');
insert into TBL_PROVEEDOR (COD_PROVEEDOR, NOM_PROVEEDOR)
values ('0004', 'OTROS');
commit;

insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0001', 'PILOTO');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0002', 'MECANICO');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0003', 'CARGA MASTER');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0004', 'CONTROLADOR AEREO');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0005', 'COLABORADOR');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0006', 'GERENTE');
insert into TBL_REPORTADOR (COD_REPORTADOR, NOM_REPORTADOR)
values ('0007', 'OTROS');
commit;
