--TABLA DE CABECERA DE CARGA
  CREATE TABLE CAB_CARGA(
  IDARCHIVO integer NOT NULL,
  IDNAVE integer NOT NULL,
  NOMBREARCHIVO VARCHAR2(225) NOT NULL,
  CANTREGISTRO integer NOT NULL,
  ESTADO CHAR(1)  default 'A' NOT NULL,
  PESOARCHIVO VARCHAR2(25) NOT NULL,
  FEC_CARGA  DATE not null ,
  PRIMARY KEY (IDARCHIVO)--LLAVE PRIMARY
  );
 --TABLA DE DETALLE DE CARGA 
  CREATE TABLE DET_CARGA(
  IDARCHIVO INTEGER NOT NULL,
  REFARCHIVO VARCHAR2(10) NOT NULL,
  FECHA DATE NOT NULL,
  DISCREPANCIA VARCHAR2(500) NOT NULL,
  ACCION VARCHAR2(500) NOT NULL,
  CODATA VARCHAR2(4) NOT NULL
  );
  
 ALTER TABLE DET_CARGA
 ADD CONSTRAINT FK_DET_CARGA FOREIGN KEY (IDARCHIVO)
 REFERENCES CAB_CARGA (IDARCHIVO);--LLAVE FORANEA
   
   --TABLA DE REGISTRO DE AERONAVES
  CREATE TABLE ECO_NAVE(
  IDNAVE INTEGER NOT NULL,
  NOMNAVE VARCHAR2(25) NOT NULL,
  FEC_CREACION  DATE   DEFAULT SYSDATE NOT NULL,
  FEC_MODIFICACION DATE,
  ESTADO CHAR(1) );
  
  ALTER TABLE ECO_NAVE ADD CONSTRAINT IDNAVE_UNIQUE UNIQUE(NOMNAVE);--EL NOMBRE DE LA NAVE DEBE SER UNICO
  ALTER TABLE ECO_NAVE ADD CONSTRAINT PK_ECO_NAVE PRIMARY KEY (IDNAVE);--LLAVE PRIMARIA DE LA TABLE DE LA AERONAVE 
  --TABLA DE PROCESAMIENTO DE PROCESAMIENTO DE  LA LA CARGA MASIVA
  CREATE TABLE HIST_PROCESAMIENTO(
  IDARCHIVO INTEGER NOT NULL,
  IDNAVE INTEGER NOT NULL,
  REFARCHIVO VARCHAR2(10) NOT NULL,
  FECHA DATE NOT NULL,
  FECHAPROCES DATE NOT NULL,
  CODATA INTEGER NOT NULL);
 --TABLA MAESTRA DE CODIGO DE ATAS

  CREATE TABLE ATAS(
  CODATA INTEGER NOT NULL,
  NOMATA VARCHAR2(100) NOT NULL,
  PRIMARY KEY (CODATA));
   --TABLA DONDE SE REGISTRA LAS HORAS VUELO DE UNA AERONAVE
   CREATE TABLE HIST_HORAS(
   COD_REGIS INTEGER NOT NULL,
   IDNAVE INTEGER NOT NULL,
   NOM_MES VARCHAR2(50) NOT NULL,
   NOM_ANO CHAR(4) NOT NULL,
   NUM_HORAS  INTEGER NOT NULL,
   FECHA   DATE NOT NULL,
   PRIMARY KEY(COD_REGIS)
   );
   ALTER TABLE HIST_HORAS
   ADD CONSTRAINT FK_HIST_HORAS FOREIGN KEY (IDNAVE)
   REFERENCES ECO_NAVE(IDNAVE);--LLAVE FORANEA DEL HISTORIAL DE HORAS CON LA TABLA AERONAVE

   
  
  
INSERT INTO ECO_NAVE(IDNAVE,NOMNAVE,FEC_CREACION,ESTADO) VALUES(1,'1996',SYSDATE,'A');

INSERT INTO ECO_NAVE(IDNAVE,NOMNAVE,FEC_CREACION,ESTADO) VALUES(2,'2035',SYSDATE,'A');

INSERT INTO ECO_NAVE(IDNAVE,NOMNAVE,FEC_CREACION,ESTADO) VALUES(3,'2081',SYSDATE,'A');

INSERT INTO ECO_NAVE(IDNAVE,NOMNAVE,FEC_CREACION,ESTADO) VALUES(4,'2082',SYSDATE,'A');

UPDATE ECO_NAVE SET FEC_CREACION=SYSDATE,FEC_MODIFICACION=SYSDATE,ESTADO ='A' WHERE IDNAVE='1';

UPDATE ECO_NAVE SET FEC_CREACION=SYSDATE,FEC_MODIFICACION=SYSDATE,ESTADO ='A' WHERE IDNAVE='2';

UPDATE ECO_NAVE SET FEC_CREACION=SYSDATE,FEC_MODIFICACION=SYSDATE,ESTADO ='A' WHERE IDNAVE='3';

UPDATE ECO_NAVE SET FEC_CREACION=SYSDATE,FEC_MODIFICACION=SYSDATE,ESTADO ='A' WHERE IDNAVE='4';
 
 CREATE SEQUENCE SEC_CODIGO
 START WITH 1
 INCREMENT BY 1 MAXVALUE 99999999 MINVALUE 1;
  
 CREATE SEQUENCE SEC_COD_HORAS
 START WITH 1
 INCREMENT BY 1 MAXVALUE 99999999 MINVALUE 1;
 
INSERT INTO ATAS (CODATA,NOMATA) VALUES(21,'Aire Acodicionado');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 22,'Piloto Automatico');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (23,'Comunicaciones');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 24,'Sistema Electrico');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 25,'Equipo y Accesorios');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 26,'Proteccion contra fuego');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 27,'Controles de vuelo');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 28,'Combustible');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 29,'Sistema Hidraulico');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 30,'Proteccion contra hielo y lluvia');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 31,'Sist. Indicaciones e Inst. de Grabacion');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(32,'Tren de aterrizaje');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(33,'Luces');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 34,'Navegacion');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 36,'Sistema Neumatico');
INSERT INTO ATAS(CODATA,NOMATA) VALUES( 39,'Electrical/ electronic panel');
INSERT INTO ATAS(CODATA,NOMATA) VALUES ( 45,'Central main System');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (51,'Estructuras');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (52,'Puertas');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (53,'Fuselaje');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (55,'Estabilizadores');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 56,'Ventanas');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (62,'Rotores');
INSERT INTO ATAS(CODATA,NOMATA) VALUES ( 63,'Impulsor de Rotor Principal');
INSERT INTO ATAS(CODATA,NOMATA) VALUES ( 64,'Rotor de Cola');
INSERT INTO ATAS(CODATA,NOMATA) VALUES ( 65,'Impulsor Rotor Cola');
INSERT INTO ATAS(CODATA,NOMATA) VALUES ( 67,'Controles de vuelo del Rotor');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (70,'Practicas Estándar del motor');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(71,'Planta motriz');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(73,'Sistema de Combustible motor');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 74,'Encendido');
INSERT INTO ATAS (CODATA,NOMATA) VALUES( 75,'Purga de aire');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(76,'Controles de motor');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (77,'Indicadores de motor');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (78,'Escape');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (79,'Lubricacion');
INSERT INTO ATAS(CODATA,NOMATA) VALUES (80,'Arranque');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(83,'Caja de engranaje');
INSERT INTO ATAS (CODATA,NOMATA) VALUES(95,'Equipamiento especial');

UPDATE ATAS SET NOMATA=UPPER(NOMATA); 
COMMIT; 
 
SELECT  * FROM  CAB_CARGA;   
SELECT  * FROM  DET_CARGA;
SELECT  * FROM  HIST_PROCESAMIENTO ;
SELECT  * FROM  ECO_NAVE;
SELECT  * FROM  ATAS;
SELECT  * FROM HIST_HORAS;
 
 



