SELECT * FROM TBL_REPORTADOR FOR UPDATE;
SELECT * FROM TBL_PROVEEDOR FOR UPDATE;
SELECT * FROM TBL_DEPARTAMENTO FOR UPDATE;
SELECT * FROM TBL_PLATAFORMA FOR UPDATE;
SELECT * FROM TBL_AREA_MOVIMIENTO FOR UPDATE;
SELECT * FROM TBL_FASE_VUELO FOR UPDATE;
SELECT * FROM TBL_AREA_RESPONSABLE FOR UPDATE;
SELECT * FROM TBL_MOV_PUBLICO FOR UPDATE;