--TABLAS MAESTRAS DE LA LOGICA DE SUCESOS-12/04/2016 BY CESAR HUANES
CREATE TABLE TBL_SUCESOS(
COD_SUCESO CHAR(10) NOT NULL PRIMARY KEY,
FEC_SUCESO DATE NOT NULL,
DES_SUCESO VARCHAR2(1000) NOT NULL,
IDNAVE INTEGER NOT NULL,
COD_REPORTADOR CHAR(4) NOT NULL,
COD_PROVEDOR CHAR(4) NOT NULL,
COD_CLASE_SUCESO CHAR(4) NOT NULL,
COD_CATEGORIA CHAR(4) NOT NULL,
COD_EVENTO CHAR(10) NOT NULL,
COD_PLATAFORMA CHAR(2) NOT NULL,
COD_FASE_VUELO CHAR(2) NOT NULL,
COD_AREA_RESPONSABLE CHAR(2) NOT NULL,
COD_MOV_PUBLICO CHAR(2) NOT NULL,
COD_ORIGEN CHAR(2) NOT NULL,
COD_DESTINO CHAR(2) NOT NULL,
COD_LUGAR_SUCESO CHAR(2) NOT NULL,
FEC_CREACION DATE DEFAULT SYSDATE NOT NULL,
USU_CREACION VARCHAR2(30),
FEC_MODIFICACION DATE ,
USU_MODIFICACION VARCHAR2(30) ,
ESTADO CHAR(1) DEFAULT 'S'
);
CREATE SEQUENCE SECUENCIA_SUCESO 
START WITH 1
INCREMENT BY 1
MAXVALUE 999999999;



CREATE TABLE TBL_REPORTADOR(
COD_REPORTADOR CHAR(4) NOT NULL PRIMARY KEY,
NOM_REPORTADOR VARCHAR2(100) NOT NULL);

ALTER TABLE TBL_REPORTADOR
ADD CONSTRAINT UNIQUE_TBL_REPORTADOR UNIQUE (NOM_REPORTADOR);

CREATE TABLE TBL_PROVEEDOR(
COD_PROVEEDOR CHAR(4) NOT NULL PRIMARY KEY,
NOM_PROVEEDOR VARCHAR2(100) NOT NULL
);
ALTER TABLE TBL_PROVEEDOR
ADD CONSTRAINT UNIQUE_TBL_PROVEEDOR UNIQUE (NOM_PROVEEDOR);


CREATE TABLE TBL_CLASE_SUCESO(
COD_CLASE_SUCESO CHAR(4) NOT NULL PRIMARY KEY,
NOM_CLASE_SUCESO VARCHAR2(50) NOT NULL,
DESC_CLASE_SUCESO  VARCHAR2(1000) NOT NULL
);
ALTER TABLE TBL_CLASE_SUCESO
ADD CONSTRAINT UNIQUE_TBL_CLASE_SUCESO UNIQUE (NOM_CLASE_SUCESO);


CREATE TABLE  TBL_CATEGORIA_SUCESO(
COD_CATEGORIA CHAR(4) NOT NULL PRIMARY KEY,
NOM_CATEGORIA VARCHAR2(200) NOT NULL
);
ALTER TABLE TBL_CATEGORIA_SUCESO
ADD CONSTRAINT UNIQUE_TBL_CATEGORIA_SUCESO UNIQUE (NOM_CATEGORIA);

CREATE TABLE TBL_EVENTO_SUCESOS(
COD_EVENTO CHAR(10) NOT NULL PRiMARY KEY,
NOM_EVENTO VARCHAR2(200) NOT NULL
);
ALTER TABLE TBL_EVENTO_SUCESOS
ADD CONSTRAINT UNIQUE_TBL_EVENTO_SUCESOS UNIQUE (NOM_EVENTO);


CREATE TABLE TBL_DEPARTAMENTO(
COD_DEPARTAMENTO CHAR(2) NOT NULL PRIMARY KEY,
NOM_DEPARTAMENTO VARCHAR2(100) NOT NULL ,
ABRE_DEPARTAMENTO CHAR(5) NOT NULL
);
ALTER TABLE TBL_DEPARTAMENTO
ADD CONSTRAINT UNIQUE_TBL_DEPARTAMENTO UNIQUE (NOM_DEPARTAMENTO,ABRE_DEPARTAMENTO);

CREATE TABLE TBL_PLATAFORMA(
COD_PLATAFORMA CHAR(2) NOT NULL PRIMARY KEY ,
NOM_PLATAFORMA  VARCHAR2(50) NOT NULL
);
ALTER TABLE TBL_PLATAFORMA
ADD CONSTRAINT UNIQUE_TBL_PLATAFORMA UNIQUE (NOM_PLATAFORMA);


CREATE TABLE TBL_FASE_VUELO(
COD_FASE_VUELO CHAR(2) NOT  NULL PRIMARY KEY,
NOM_FASE_VUELO VARCHAR2(50) NOT NULL,
ABRE_FASE_VUELO  CHAR(5) NOT NULL

);
ALTER TABLE TBL_FASE_VUELO
ADD CONSTRAINT UNIQUE_TBL_FASE_VUELO UNIQUE (NOM_FASE_VUELO,ABRE_FASE_VUELO);


CREATE TABLE TBL_AREA_RESPONSABLE(
COD_AREA_RESPONSABLE CHAR(2) NOT NULL PRIMARY KEY,
NOM_AREA_RESPONSABLE VARCHAR2(50) NOT NULL
);
ALTER TABLE TBL_AREA_RESPONSABLE
ADD CONSTRAINT UNIQUE_TBL_AREA_RESPONSABLE UNIQUE (NOM_AREA_RESPONSABLE);


CREATE TABLE TBL_MOV_PUBLICO(
COD_MOV_PUBLICO CHAR(2) NOT NULL PRIMARY KEY,
NOM_MOV_PUBLICO VARCHAR2(50) NOT NULL
);
ALTER TABLE TBL_MOV_PUBLICO
ADD CONSTRAINT UNIQUE_TBL_MOV_PUBLICO UNIQUE (NOM_MOV_PUBLICO);
