
-- SCRIPT DE GESTION DE PELIGROS...BY CESAR HUANES 12/04/2016
CREATE TABLE TBL_REGISTRO_PELIGROS(
CODIGO_REGISTRO  CHAR(10) PRIMARY KEY NOT NULL,
IDNAVE INTEGER NOT NULL,
FECHA_INCIDENCIA DATE NOT NULL,
COD_DEPARTAMENTO CHAR(2) NOT NULL,
COD_AREA_RESPONSABLE CHAR(2) NOT NULL,
DESCRIPCION VARCHAR2(300) NOT NULL,
PELIGRO VARCHAR2(300) NOT NULL,
CONSECUENCIA VARCHAR2(300) NOT NULL,
DEFENSA_MR VARCHAR(300) NOT NULL,
INDICE_RIESGO CHAR(2) NOT NULL,
ACCION_MR VARCHAR2(300) NOT NULL,
INDICE_RIESGO2 CHAR(2) NOT NULL,
DNI  CHAR(8) NOT NULL,
ACCION_TOMADA VARCHAR2(300) NOT NULL,
OBSERVACION VARCHAR2(300) NOT NULL,
FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
USU_CREACION VARCHAR2(50) NOT NULL,
FECHA_MODIFICACION DATE,
USU_MODIFICACION VARCHAR2(50)
);



CREATE TABLE TBL_PROBABILIDAD_EVENTO(
PROBABILIDAD INTEGER PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL
);


CREATE TABLE TBL_SEVERIDAD_EVENTO(
SEVERIDAD CHAR(1) PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL
);

SELECT  * FROM TBL_PROBABILIDAD_EVENTO;
SELECT * FROM TBL_SEVERIDAD_EVENTO;
